-- ==========================================================================
-- bookstore — Online book publishing and sales — catalogue, customers, wishlists, orders
-- GENERATED by tools/build_datasets.py — do not edit by hand.
-- Dialect: sqlite. Tables: 11. Rows: 110.
-- ==========================================================================

PRAGMA foreign_keys = OFF;
BEGIN TRANSACTION;

DROP TABLE IF EXISTS order_book;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS wishlist;
DROP TABLE IF EXISTS address;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS bookauthor;
DROP TABLE IF EXISTS author;
DROP TABLE IF EXISTS bookgenre;
DROP TABLE IF EXISTS genre;
DROP TABLE IF EXISTS book;
DROP TABLE IF EXISTS publisher;

CREATE TABLE publisher (
    publisherid INTEGER NOT NULL,
    name TEXT NOT NULL,
    contactdetails TEXT,
    CONSTRAINT pk_publisher PRIMARY KEY (publisherid)
);

CREATE TABLE book (
    bookid INTEGER NOT NULL,
    title TEXT NOT NULL,
    isbn TEXT NOT NULL,
    edition INTEGER NOT NULL,
    publicationyear INTEGER,
    price NUMERIC,
    publisherid INTEGER,
    CONSTRAINT pk_book PRIMARY KEY (bookid),
    CONSTRAINT fk_book_1 FOREIGN KEY (publisherid) REFERENCES publisher (publisherid)
);

CREATE TABLE genre (
    genreid INTEGER NOT NULL,
    genrename TEXT NOT NULL,
    CONSTRAINT pk_genre PRIMARY KEY (genreid)
);

CREATE TABLE bookgenre (
    bookid INTEGER NOT NULL,
    genreid INTEGER NOT NULL,
    CONSTRAINT pk_bookgenre PRIMARY KEY (bookid, genreid),
    CONSTRAINT fk_bookgenre_1 FOREIGN KEY (bookid) REFERENCES book (bookid),
    CONSTRAINT fk_bookgenre_2 FOREIGN KEY (genreid) REFERENCES genre (genreid)
);

CREATE TABLE author (
    authorid INTEGER NOT NULL,
    name TEXT NOT NULL,
    biography TEXT,
    CONSTRAINT pk_author PRIMARY KEY (authorid)
);

CREATE TABLE bookauthor (
    bookid INTEGER NOT NULL,
    authorid INTEGER NOT NULL,
    CONSTRAINT pk_bookauthor PRIMARY KEY (bookid, authorid),
    CONSTRAINT fk_bookauthor_1 FOREIGN KEY (bookid) REFERENCES book (bookid),
    CONSTRAINT fk_bookauthor_2 FOREIGN KEY (authorid) REFERENCES author (authorid)
);

CREATE TABLE customer (
    customerid INTEGER NOT NULL,
    name TEXT NOT NULL,
    CONSTRAINT pk_customer PRIMARY KEY (customerid)
);

CREATE TABLE address (
    addressid INTEGER NOT NULL,
    customerid INTEGER,
    street TEXT,
    city TEXT,
    state TEXT,
    country TEXT,
    CONSTRAINT pk_address PRIMARY KEY (addressid),
    CONSTRAINT fk_address_1 FOREIGN KEY (customerid) REFERENCES customer (customerid)
);

CREATE TABLE wishlist (
    customerid INTEGER NOT NULL,
    bookid INTEGER NOT NULL,
    CONSTRAINT pk_wishlist PRIMARY KEY (customerid, bookid),
    CONSTRAINT fk_wishlist_1 FOREIGN KEY (customerid) REFERENCES customer (customerid),
    CONSTRAINT fk_wishlist_2 FOREIGN KEY (bookid) REFERENCES book (bookid)
);

CREATE TABLE orders (
    orderid INTEGER NOT NULL,
    orderdate TEXT NOT NULL,
    customerid INTEGER,
    paymentdetails TEXT,
    shipmentstatus TEXT,
    shipmentaddressid INTEGER,
    CONSTRAINT pk_orders PRIMARY KEY (orderid),
    CONSTRAINT fk_orders_1 FOREIGN KEY (customerid) REFERENCES customer (customerid),
    CONSTRAINT fk_orders_2 FOREIGN KEY (shipmentaddressid) REFERENCES address (addressid)
);

CREATE TABLE order_book (
    orderitemid INTEGER NOT NULL,
    orderid INTEGER,
    bookid INTEGER,
    quantity INTEGER NOT NULL,
    itemdiscount NUMERIC,
    CONSTRAINT pk_order_book PRIMARY KEY (orderitemid),
    CONSTRAINT fk_order_book_1 FOREIGN KEY (orderid) REFERENCES orders (orderid),
    CONSTRAINT fk_order_book_2 FOREIGN KEY (bookid) REFERENCES book (bookid)
);

-- publisher: 10 rows
INSERT INTO publisher (publisherid, name, contactdetails) VALUES
  (1, 'Penguin Random House', 'contact@penguinrandomhouse.com'),
  (2, 'HarperCollins', 'info@harpercollins.com'),
  (3, 'Macmillan Publishers', 'support@macmillan.com'),
  (4, 'Simon & Schuster', 'help@simonandschuster.com'),
  (5, 'Hachette Livre', 'contact@hachette.com'),
  (6, 'Scholastic', 'info@scholastic.com'),
  (7, 'Pearson', 'support@pearson.com'),
  (8, 'Oxford University Press', 'contact@oup.com'),
  (9, 'Wiley', 'info@wiley.com'),
  (10, 'Cambridge University Press', 'support@cambridge.org');

-- book: 10 rows
INSERT INTO book (bookid, title, isbn, edition, publicationyear, price, publisherid) VALUES
  (1, 'To Kill a Mockingbird', '9780060935467', 1, 1960, 15.99, 2),
  (2, '1984', '9780451524935', 1, 1949, 12.99, 1),
  (3, 'The Great Gatsby', '9780743273565', 1, 1925, 10.99, 4),
  (4, 'Pride and Prejudice', '9780141439518', 2, 1813, 9.99, 8),
  (5, 'Moby-Dick', '9780142437247', 1, 1851, 11.99, 8),
  (6, 'The Catcher in the Rye', '9780316769488', 1, 1951, 8.99, 7),
  (7, 'Jane Eyre', '9780141441146', 3, 1847, 10.49, 8),
  (8, 'Wuthering Heights', '9780141439556', 2, 1847, 9.49, 8),
  (9, 'Frankenstein', '9780486282114', 1, 1818, 6.99, 10),
  (10, 'Animal Farm', '9780451526342', 1, 1945, 7.99, 1);

-- genre: 10 rows
INSERT INTO genre (genreid, genrename) VALUES
  (1, 'Fiction'),
  (2, 'Science Fiction'),
  (3, 'Fantasy'),
  (4, 'Romance'),
  (5, 'Historical'),
  (6, 'Mystery'),
  (7, 'Thriller'),
  (8, 'Horror'),
  (9, 'Biography'),
  (10, 'Philosophy');

-- bookgenre: 10 rows
INSERT INTO bookgenre (bookid, genreid) VALUES
  (1, 1),
  (2, 1),
  (3, 1),
  (4, 4),
  (5, 5),
  (6, 1),
  (7, 4),
  (8, 4),
  (9, 8),
  (10, 1);

-- author: 10 rows
INSERT INTO author (authorid, name, biography) VALUES
  (1, 'Harper Lee', 'American novelist known for To Kill a Mockingbird.'),
  (2, 'George Orwell', 'British author and journalist, famous for 1984 and Animal Farm.'),
  (3, 'F. Scott Fitzgerald', 'American novelist and short story writer.'),
  (4, 'Jane Austen', 'English novelist known for romantic fiction.'),
  (5, 'Herman Melville', 'American novelist and poet, known for Moby-Dick.'),
  (6, 'J.D. Salinger', 'American writer, known for The Catcher in the Rye.'),
  (7, 'Charlotte Brontë', 'English novelist and poet.'),
  (8, 'Emily Brontë', 'English novelist and poet, known for Wuthering Heights.'),
  (9, 'Mary Shelley', 'English novelist, known for Frankenstein.'),
  (10, 'Aldous Huxley', 'English writer, philosopher, and author of Brave New World.');

-- bookauthor: 10 rows
INSERT INTO bookauthor (bookid, authorid) VALUES
  (1, 1),
  (2, 2),
  (3, 3),
  (4, 4),
  (5, 5),
  (6, 6),
  (7, 7),
  (8, 8),
  (9, 9),
  (10, 2);

-- customer: 10 rows
INSERT INTO customer (customerid, name) VALUES
  (1, 'Alice Johnson'),
  (2, 'Bob Smith'),
  (3, 'Charlie Brown'),
  (4, 'Diana Prince'),
  (5, 'Eve Adams'),
  (6, 'Frank Castle'),
  (7, 'Grace Hopper'),
  (8, 'Hank Pym'),
  (9, 'Ivy League'),
  (10, 'Jack Ryan');

-- address: 10 rows
INSERT INTO address (addressid, customerid, street, city, state, country) VALUES
  (1, 1, '123 Maple Street', 'New York', 'NY', 'USA'),
  (2, 2, '456 Oak Avenue', 'Los Angeles', 'CA', 'USA'),
  (3, 3, '789 Pine Road', 'Chicago', 'IL', 'USA'),
  (4, 4, '101 Birch Blvd', 'Houston', 'TX', 'USA'),
  (5, 5, '202 Cedar Lane', 'Phoenix', 'AZ', 'USA'),
  (6, 6, '303 Elm Drive', 'Philadelphia', 'PA', 'USA'),
  (7, 7, '404 Walnut Way', 'San Antonio', 'TX', 'USA'),
  (8, 8, '505 Chestnut Circle', 'San Diego', 'CA', 'USA'),
  (9, 9, '606 Spruce Court', 'Dallas', 'TX', 'USA'),
  (10, 10, '707 Fir Place', 'San Jose', 'CA', 'USA');

-- wishlist: 10 rows
INSERT INTO wishlist (customerid, bookid) VALUES
  (1, 1),
  (1, 2),
  (2, 3),
  (3, 4),
  (4, 5),
  (5, 6),
  (6, 7),
  (7, 8),
  (8, 9),
  (9, 10);

-- orders: 10 rows
INSERT INTO orders (orderid, orderdate, customerid, paymentdetails, shipmentstatus, shipmentaddressid) VALUES
  (1, '2023-06-01', 1, 'Credit Card', 'Shipped', 1),
  (2, '2023-06-02', 2, 'PayPal', 'Processing', 2),
  (3, '2023-06-03', 3, 'Debit Card', 'Delivered', 3),
  (4, '2023-06-04', 4, 'Net Banking', 'Shipped', 4),
  (5, '2023-06-05', 5, 'Credit Card', 'Processing', 5),
  (6, '2023-06-06', 6, 'PayPal', 'Delivered', 6),
  (7, '2023-06-07', 7, 'Credit Card', 'Shipped', 7),
  (8, '2023-06-08', 8, 'Debit Card', 'Processing', 8),
  (9, '2023-06-09', 9, 'Net Banking', 'Delivered', 9),
  (10, '2023-06-10', 10, 'Credit Card', 'Shipped', 10);

-- order_book: 10 rows
INSERT INTO order_book (orderitemid, orderid, bookid, quantity, itemdiscount) VALUES
  (1, 1, 1, 1, 0.0),
  (2, 2, 2, 2, 5.0),
  (3, 3, 3, 1, 10.0),
  (4, 4, 4, 3, 0.0),
  (5, 5, 5, 2, 15.0),
  (6, 6, 6, 1, 0.0),
  (7, 7, 7, 2, 5.0),
  (8, 8, 8, 1, 10.0),
  (9, 9, 9, 3, 0.0),
  (10, 10, 10, 2, 15.0);

COMMIT;
PRAGMA foreign_keys = ON;
