-- ==========================================================================
-- bookstore — Online book publishing and sales — catalogue, customers, wishlists, orders
-- GENERATED by tools/build_datasets.py — do not edit by hand.
-- Dialect: mssql. Tables: 11. Rows: 110.
-- ==========================================================================

IF DB_ID(N'Bookstore') IS NULL CREATE DATABASE [Bookstore];
GO
USE [Bookstore];
GO
IF SCHEMA_ID(N'bookstore') IS NULL EXEC('CREATE SCHEMA [bookstore]');
GO
SET NOCOUNT ON;
GO

DECLARE @drop_fks nvarchar(max) = N'';
SELECT @drop_fks = @drop_fks + N'ALTER TABLE [' + s.name + N'].[' + t.name + N'] DROP CONSTRAINT [' + fk.name + N'];'
  FROM sys.foreign_keys fk
  JOIN sys.tables t   ON t.object_id = fk.parent_object_id
  JOIN sys.schemas s  ON s.schema_id = t.schema_id
 WHERE s.name = N'bookstore';
EXEC sp_executesql @drop_fks;
GO

IF OBJECT_ID(N'[bookstore].[order_book]', N'U') IS NOT NULL DROP TABLE [bookstore].[order_book];
IF OBJECT_ID(N'[bookstore].[orders]', N'U') IS NOT NULL DROP TABLE [bookstore].[orders];
IF OBJECT_ID(N'[bookstore].[wishlist]', N'U') IS NOT NULL DROP TABLE [bookstore].[wishlist];
IF OBJECT_ID(N'[bookstore].[address]', N'U') IS NOT NULL DROP TABLE [bookstore].[address];
IF OBJECT_ID(N'[bookstore].[customer]', N'U') IS NOT NULL DROP TABLE [bookstore].[customer];
IF OBJECT_ID(N'[bookstore].[bookauthor]', N'U') IS NOT NULL DROP TABLE [bookstore].[bookauthor];
IF OBJECT_ID(N'[bookstore].[author]', N'U') IS NOT NULL DROP TABLE [bookstore].[author];
IF OBJECT_ID(N'[bookstore].[bookgenre]', N'U') IS NOT NULL DROP TABLE [bookstore].[bookgenre];
IF OBJECT_ID(N'[bookstore].[genre]', N'U') IS NOT NULL DROP TABLE [bookstore].[genre];
IF OBJECT_ID(N'[bookstore].[book]', N'U') IS NOT NULL DROP TABLE [bookstore].[book];
IF OBJECT_ID(N'[bookstore].[publisher]', N'U') IS NOT NULL DROP TABLE [bookstore].[publisher];
GO

CREATE TABLE [bookstore].[publisher] (
    [publisherid] INT NOT NULL,
    [name] NVARCHAR(100) NOT NULL,
    [contactdetails] NVARCHAR(255),
    CONSTRAINT pk_publisher PRIMARY KEY ([publisherid])
);
GO

CREATE TABLE [bookstore].[book] (
    [bookid] INT NOT NULL,
    [title] NVARCHAR(200) NOT NULL,
    [isbn] NVARCHAR(20) NOT NULL,
    [edition] INT NOT NULL,
    [publicationyear] INT,
    [price] DECIMAL(10,2),
    [publisherid] INT,
    CONSTRAINT pk_book PRIMARY KEY ([bookid]),
    CONSTRAINT fk_book_1 FOREIGN KEY ([publisherid]) REFERENCES [bookstore].[publisher] ([publisherid])
);
GO

CREATE TABLE [bookstore].[genre] (
    [genreid] INT NOT NULL,
    [genrename] NVARCHAR(100) NOT NULL,
    CONSTRAINT pk_genre PRIMARY KEY ([genreid])
);
GO

CREATE TABLE [bookstore].[bookgenre] (
    [bookid] INT NOT NULL,
    [genreid] INT NOT NULL,
    CONSTRAINT pk_bookgenre PRIMARY KEY ([bookid], [genreid]),
    CONSTRAINT fk_bookgenre_1 FOREIGN KEY ([bookid]) REFERENCES [bookstore].[book] ([bookid]),
    CONSTRAINT fk_bookgenre_2 FOREIGN KEY ([genreid]) REFERENCES [bookstore].[genre] ([genreid])
);
GO

CREATE TABLE [bookstore].[author] (
    [authorid] INT NOT NULL,
    [name] NVARCHAR(100) NOT NULL,
    [biography] NVARCHAR(4000),
    CONSTRAINT pk_author PRIMARY KEY ([authorid])
);
GO

CREATE TABLE [bookstore].[bookauthor] (
    [bookid] INT NOT NULL,
    [authorid] INT NOT NULL,
    CONSTRAINT pk_bookauthor PRIMARY KEY ([bookid], [authorid]),
    CONSTRAINT fk_bookauthor_1 FOREIGN KEY ([bookid]) REFERENCES [bookstore].[book] ([bookid]),
    CONSTRAINT fk_bookauthor_2 FOREIGN KEY ([authorid]) REFERENCES [bookstore].[author] ([authorid])
);
GO

CREATE TABLE [bookstore].[customer] (
    [customerid] INT NOT NULL,
    [name] NVARCHAR(100) NOT NULL,
    CONSTRAINT pk_customer PRIMARY KEY ([customerid])
);
GO

CREATE TABLE [bookstore].[address] (
    [addressid] INT NOT NULL,
    [customerid] INT,
    [street] NVARCHAR(100),
    [city] NVARCHAR(100),
    [state] NVARCHAR(100),
    [country] NVARCHAR(100),
    CONSTRAINT pk_address PRIMARY KEY ([addressid]),
    CONSTRAINT fk_address_1 FOREIGN KEY ([customerid]) REFERENCES [bookstore].[customer] ([customerid])
);
GO

CREATE TABLE [bookstore].[wishlist] (
    [customerid] INT NOT NULL,
    [bookid] INT NOT NULL,
    CONSTRAINT pk_wishlist PRIMARY KEY ([customerid], [bookid]),
    CONSTRAINT fk_wishlist_1 FOREIGN KEY ([customerid]) REFERENCES [bookstore].[customer] ([customerid]),
    CONSTRAINT fk_wishlist_2 FOREIGN KEY ([bookid]) REFERENCES [bookstore].[book] ([bookid])
);
GO

CREATE TABLE [bookstore].[orders] (
    [orderid] INT NOT NULL,
    [orderdate] DATE NOT NULL,
    [customerid] INT,
    [paymentdetails] NVARCHAR(255),
    [shipmentstatus] NVARCHAR(50),
    [shipmentaddressid] INT,
    CONSTRAINT pk_orders PRIMARY KEY ([orderid]),
    CONSTRAINT fk_orders_1 FOREIGN KEY ([customerid]) REFERENCES [bookstore].[customer] ([customerid]),
    CONSTRAINT fk_orders_2 FOREIGN KEY ([shipmentaddressid]) REFERENCES [bookstore].[address] ([addressid])
);
GO

CREATE TABLE [bookstore].[order_book] (
    [orderitemid] INT NOT NULL,
    [orderid] INT,
    [bookid] INT,
    [quantity] INT NOT NULL,
    [itemdiscount] DECIMAL(5,2),
    CONSTRAINT pk_order_book PRIMARY KEY ([orderitemid]),
    CONSTRAINT fk_order_book_1 FOREIGN KEY ([orderid]) REFERENCES [bookstore].[orders] ([orderid]),
    CONSTRAINT fk_order_book_2 FOREIGN KEY ([bookid]) REFERENCES [bookstore].[book] ([bookid])
);
GO

-- publisher: 10 rows
INSERT INTO [bookstore].[publisher] ([publisherid], [name], [contactdetails]) VALUES
  (1, N'Penguin Random House', N'contact@penguinrandomhouse.com'),
  (2, N'HarperCollins', N'info@harpercollins.com'),
  (3, N'Macmillan Publishers', N'support@macmillan.com'),
  (4, N'Simon & Schuster', N'help@simonandschuster.com'),
  (5, N'Hachette Livre', N'contact@hachette.com'),
  (6, N'Scholastic', N'info@scholastic.com'),
  (7, N'Pearson', N'support@pearson.com'),
  (8, N'Oxford University Press', N'contact@oup.com'),
  (9, N'Wiley', N'info@wiley.com'),
  (10, N'Cambridge University Press', N'support@cambridge.org');
GO

-- book: 10 rows
INSERT INTO [bookstore].[book] ([bookid], [title], [isbn], [edition], [publicationyear], [price], [publisherid]) VALUES
  (1, N'To Kill a Mockingbird', N'9780060935467', 1, 1960, 15.99, 2),
  (2, N'1984', N'9780451524935', 1, 1949, 12.99, 1),
  (3, N'The Great Gatsby', N'9780743273565', 1, 1925, 10.99, 4),
  (4, N'Pride and Prejudice', N'9780141439518', 2, 1813, 9.99, 8),
  (5, N'Moby-Dick', N'9780142437247', 1, 1851, 11.99, 8),
  (6, N'The Catcher in the Rye', N'9780316769488', 1, 1951, 8.99, 7),
  (7, N'Jane Eyre', N'9780141441146', 3, 1847, 10.49, 8),
  (8, N'Wuthering Heights', N'9780141439556', 2, 1847, 9.49, 8),
  (9, N'Frankenstein', N'9780486282114', 1, 1818, 6.99, 10),
  (10, N'Animal Farm', N'9780451526342', 1, 1945, 7.99, 1);
GO

-- genre: 10 rows
INSERT INTO [bookstore].[genre] ([genreid], [genrename]) VALUES
  (1, N'Fiction'),
  (2, N'Science Fiction'),
  (3, N'Fantasy'),
  (4, N'Romance'),
  (5, N'Historical'),
  (6, N'Mystery'),
  (7, N'Thriller'),
  (8, N'Horror'),
  (9, N'Biography'),
  (10, N'Philosophy');
GO

-- bookgenre: 10 rows
INSERT INTO [bookstore].[bookgenre] ([bookid], [genreid]) VALUES
  (1, 1),
  (2, 1),
  (3, 1),
  (4, 4),
  (5, 5),
  (6, 1),
  (7, 4),
  (8, 4),
  (9, 8),
  (10, 1);
GO

-- author: 10 rows
INSERT INTO [bookstore].[author] ([authorid], [name], [biography]) VALUES
  (1, N'Harper Lee', N'American novelist known for To Kill a Mockingbird.'),
  (2, N'George Orwell', N'British author and journalist, famous for 1984 and Animal Farm.'),
  (3, N'F. Scott Fitzgerald', N'American novelist and short story writer.'),
  (4, N'Jane Austen', N'English novelist known for romantic fiction.'),
  (5, N'Herman Melville', N'American novelist and poet, known for Moby-Dick.'),
  (6, N'J.D. Salinger', N'American writer, known for The Catcher in the Rye.'),
  (7, N'Charlotte Brontë', N'English novelist and poet.'),
  (8, N'Emily Brontë', N'English novelist and poet, known for Wuthering Heights.'),
  (9, N'Mary Shelley', N'English novelist, known for Frankenstein.'),
  (10, N'Aldous Huxley', N'English writer, philosopher, and author of Brave New World.');
GO

-- bookauthor: 10 rows
INSERT INTO [bookstore].[bookauthor] ([bookid], [authorid]) VALUES
  (1, 1),
  (2, 2),
  (3, 3),
  (4, 4),
  (5, 5),
  (6, 6),
  (7, 7),
  (8, 8),
  (9, 9),
  (10, 2);
GO

-- customer: 10 rows
INSERT INTO [bookstore].[customer] ([customerid], [name]) VALUES
  (1, N'Alice Johnson'),
  (2, N'Bob Smith'),
  (3, N'Charlie Brown'),
  (4, N'Diana Prince'),
  (5, N'Eve Adams'),
  (6, N'Frank Castle'),
  (7, N'Grace Hopper'),
  (8, N'Hank Pym'),
  (9, N'Ivy League'),
  (10, N'Jack Ryan');
GO

-- address: 10 rows
INSERT INTO [bookstore].[address] ([addressid], [customerid], [street], [city], [state], [country]) VALUES
  (1, 1, N'123 Maple Street', N'New York', N'NY', N'USA'),
  (2, 2, N'456 Oak Avenue', N'Los Angeles', N'CA', N'USA'),
  (3, 3, N'789 Pine Road', N'Chicago', N'IL', N'USA'),
  (4, 4, N'101 Birch Blvd', N'Houston', N'TX', N'USA'),
  (5, 5, N'202 Cedar Lane', N'Phoenix', N'AZ', N'USA'),
  (6, 6, N'303 Elm Drive', N'Philadelphia', N'PA', N'USA'),
  (7, 7, N'404 Walnut Way', N'San Antonio', N'TX', N'USA'),
  (8, 8, N'505 Chestnut Circle', N'San Diego', N'CA', N'USA'),
  (9, 9, N'606 Spruce Court', N'Dallas', N'TX', N'USA'),
  (10, 10, N'707 Fir Place', N'San Jose', N'CA', N'USA');
GO

-- wishlist: 10 rows
INSERT INTO [bookstore].[wishlist] ([customerid], [bookid]) VALUES
  (1, 1),
  (1, 2),
  (2, 3),
  (3, 4),
  (4, 5),
  (5, 6),
  (6, 7),
  (7, 8),
  (8, 9),
  (9, 10);
GO

-- orders: 10 rows
INSERT INTO [bookstore].[orders] ([orderid], [orderdate], [customerid], [paymentdetails], [shipmentstatus], [shipmentaddressid]) VALUES
  (1, '2023-06-01', 1, N'Credit Card', N'Shipped', 1),
  (2, '2023-06-02', 2, N'PayPal', N'Processing', 2),
  (3, '2023-06-03', 3, N'Debit Card', N'Delivered', 3),
  (4, '2023-06-04', 4, N'Net Banking', N'Shipped', 4),
  (5, '2023-06-05', 5, N'Credit Card', N'Processing', 5),
  (6, '2023-06-06', 6, N'PayPal', N'Delivered', 6),
  (7, '2023-06-07', 7, N'Credit Card', N'Shipped', 7),
  (8, '2023-06-08', 8, N'Debit Card', N'Processing', 8),
  (9, '2023-06-09', 9, N'Net Banking', N'Delivered', 9),
  (10, '2023-06-10', 10, N'Credit Card', N'Shipped', 10);
GO

-- order_book: 10 rows
INSERT INTO [bookstore].[order_book] ([orderitemid], [orderid], [bookid], [quantity], [itemdiscount]) VALUES
  (1, 1, 1, 1, 0.0),
  (2, 2, 2, 2, 5.0),
  (3, 3, 3, 1, 10.0),
  (4, 4, 4, 3, 0.0),
  (5, 5, 5, 2, 15.0),
  (6, 6, 6, 1, 0.0),
  (7, 7, 7, 2, 5.0),
  (8, 8, 8, 1, 10.0),
  (9, 9, 9, 3, 0.0),
  (10, 10, 10, 2, 15.0);
GO

GO
