-- ==========================================================================
-- bookstore — Online book publishing and sales — catalogue, customers, wishlists, orders
-- GENERATED by tools/build_datasets.py — do not edit by hand.
-- Dialect: oracle. Tables: 11. Rows: 110.
-- ==========================================================================

SET DEFINE OFF
SET SQLBLANKLINES ON
SET FEEDBACK OFF

BEGIN
    FOR r IN (SELECT table_name FROM user_tables WHERE table_name IN ('ORDER_BOOK', 'ORDERS', 'WISHLIST', 'ADDRESS', 'CUSTOMER', 'BOOKAUTHOR', 'AUTHOR', 'BOOKGENRE', 'GENRE', 'BOOK', 'PUBLISHER')) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE "' || r.table_name || '" CASCADE CONSTRAINTS';
    END LOOP;
END;
/

CREATE TABLE publisher (
    publisherid NUMBER(10) NOT NULL,
    name VARCHAR2(100) NOT NULL,
    contactdetails VARCHAR2(255),
    CONSTRAINT pk_publisher PRIMARY KEY (publisherid)
);

CREATE TABLE book (
    bookid NUMBER(10) NOT NULL,
    title VARCHAR2(200) NOT NULL,
    isbn VARCHAR2(20) NOT NULL,
    edition NUMBER(10) NOT NULL,
    publicationyear NUMBER(10),
    price NUMBER(10,2),
    publisherid NUMBER(10),
    CONSTRAINT pk_book PRIMARY KEY (bookid),
    CONSTRAINT fk_book_1 FOREIGN KEY (publisherid) REFERENCES publisher (publisherid)
);

CREATE TABLE genre (
    genreid NUMBER(10) NOT NULL,
    genrename VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_genre PRIMARY KEY (genreid)
);

CREATE TABLE bookgenre (
    bookid NUMBER(10) NOT NULL,
    genreid NUMBER(10) NOT NULL,
    CONSTRAINT pk_bookgenre PRIMARY KEY (bookid, genreid),
    CONSTRAINT fk_bookgenre_1 FOREIGN KEY (bookid) REFERENCES book (bookid),
    CONSTRAINT fk_bookgenre_2 FOREIGN KEY (genreid) REFERENCES genre (genreid)
);

CREATE TABLE author (
    authorid NUMBER(10) NOT NULL,
    name VARCHAR2(100) NOT NULL,
    biography VARCHAR2(4000),
    CONSTRAINT pk_author PRIMARY KEY (authorid)
);

CREATE TABLE bookauthor (
    bookid NUMBER(10) NOT NULL,
    authorid NUMBER(10) NOT NULL,
    CONSTRAINT pk_bookauthor PRIMARY KEY (bookid, authorid),
    CONSTRAINT fk_bookauthor_1 FOREIGN KEY (bookid) REFERENCES book (bookid),
    CONSTRAINT fk_bookauthor_2 FOREIGN KEY (authorid) REFERENCES author (authorid)
);

CREATE TABLE customer (
    customerid NUMBER(10) NOT NULL,
    name VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_customer PRIMARY KEY (customerid)
);

CREATE TABLE address (
    addressid NUMBER(10) NOT NULL,
    customerid NUMBER(10),
    street VARCHAR2(100),
    city VARCHAR2(100),
    state VARCHAR2(100),
    country VARCHAR2(100),
    CONSTRAINT pk_address PRIMARY KEY (addressid),
    CONSTRAINT fk_address_1 FOREIGN KEY (customerid) REFERENCES customer (customerid)
);

CREATE TABLE wishlist (
    customerid NUMBER(10) NOT NULL,
    bookid NUMBER(10) NOT NULL,
    CONSTRAINT pk_wishlist PRIMARY KEY (customerid, bookid),
    CONSTRAINT fk_wishlist_1 FOREIGN KEY (customerid) REFERENCES customer (customerid),
    CONSTRAINT fk_wishlist_2 FOREIGN KEY (bookid) REFERENCES book (bookid)
);

CREATE TABLE orders (
    orderid NUMBER(10) NOT NULL,
    orderdate DATE NOT NULL,
    customerid NUMBER(10),
    paymentdetails VARCHAR2(255),
    shipmentstatus VARCHAR2(50),
    shipmentaddressid NUMBER(10),
    CONSTRAINT pk_orders PRIMARY KEY (orderid),
    CONSTRAINT fk_orders_1 FOREIGN KEY (customerid) REFERENCES customer (customerid),
    CONSTRAINT fk_orders_2 FOREIGN KEY (shipmentaddressid) REFERENCES address (addressid)
);

CREATE TABLE order_book (
    orderitemid NUMBER(10) NOT NULL,
    orderid NUMBER(10),
    bookid NUMBER(10),
    quantity NUMBER(10) NOT NULL,
    itemdiscount NUMBER(5,2),
    CONSTRAINT pk_order_book PRIMARY KEY (orderitemid),
    CONSTRAINT fk_order_book_1 FOREIGN KEY (orderid) REFERENCES orders (orderid),
    CONSTRAINT fk_order_book_2 FOREIGN KEY (bookid) REFERENCES book (bookid)
);

-- publisher: 10 rows
INSERT ALL
  INTO publisher VALUES (1, 'Penguin Random House', 'contact@penguinrandomhouse.com')
  INTO publisher VALUES (2, 'HarperCollins', 'info@harpercollins.com')
  INTO publisher VALUES (3, 'Macmillan Publishers', 'support@macmillan.com')
  INTO publisher VALUES (4, 'Simon & Schuster', 'help@simonandschuster.com')
  INTO publisher VALUES (5, 'Hachette Livre', 'contact@hachette.com')
  INTO publisher VALUES (6, 'Scholastic', 'info@scholastic.com')
  INTO publisher VALUES (7, 'Pearson', 'support@pearson.com')
  INTO publisher VALUES (8, 'Oxford University Press', 'contact@oup.com')
  INTO publisher VALUES (9, 'Wiley', 'info@wiley.com')
  INTO publisher VALUES (10, 'Cambridge University Press', 'support@cambridge.org')
SELECT * FROM dual;

-- book: 10 rows
INSERT ALL
  INTO book VALUES (1, 'To Kill a Mockingbird', '9780060935467', 1, 1960, 15.99, 2)
  INTO book VALUES (2, '1984', '9780451524935', 1, 1949, 12.99, 1)
  INTO book VALUES (3, 'The Great Gatsby', '9780743273565', 1, 1925, 10.99, 4)
  INTO book VALUES (4, 'Pride and Prejudice', '9780141439518', 2, 1813, 9.99, 8)
  INTO book VALUES (5, 'Moby-Dick', '9780142437247', 1, 1851, 11.99, 8)
  INTO book VALUES (6, 'The Catcher in the Rye', '9780316769488', 1, 1951, 8.99, 7)
  INTO book VALUES (7, 'Jane Eyre', '9780141441146', 3, 1847, 10.49, 8)
  INTO book VALUES (8, 'Wuthering Heights', '9780141439556', 2, 1847, 9.49, 8)
  INTO book VALUES (9, 'Frankenstein', '9780486282114', 1, 1818, 6.99, 10)
  INTO book VALUES (10, 'Animal Farm', '9780451526342', 1, 1945, 7.99, 1)
SELECT * FROM dual;

-- genre: 10 rows
INSERT ALL
  INTO genre VALUES (1, 'Fiction')
  INTO genre VALUES (2, 'Science Fiction')
  INTO genre VALUES (3, 'Fantasy')
  INTO genre VALUES (4, 'Romance')
  INTO genre VALUES (5, 'Historical')
  INTO genre VALUES (6, 'Mystery')
  INTO genre VALUES (7, 'Thriller')
  INTO genre VALUES (8, 'Horror')
  INTO genre VALUES (9, 'Biography')
  INTO genre VALUES (10, 'Philosophy')
SELECT * FROM dual;

-- bookgenre: 10 rows
INSERT ALL
  INTO bookgenre VALUES (1, 1)
  INTO bookgenre VALUES (2, 1)
  INTO bookgenre VALUES (3, 1)
  INTO bookgenre VALUES (4, 4)
  INTO bookgenre VALUES (5, 5)
  INTO bookgenre VALUES (6, 1)
  INTO bookgenre VALUES (7, 4)
  INTO bookgenre VALUES (8, 4)
  INTO bookgenre VALUES (9, 8)
  INTO bookgenre VALUES (10, 1)
SELECT * FROM dual;

-- author: 10 rows
INSERT ALL
  INTO author VALUES (1, 'Harper Lee', 'American novelist known for To Kill a Mockingbird.')
  INTO author VALUES (2, 'George Orwell', 'British author and journalist, famous for 1984 and Animal Farm.')
  INTO author VALUES (3, 'F. Scott Fitzgerald', 'American novelist and short story writer.')
  INTO author VALUES (4, 'Jane Austen', 'English novelist known for romantic fiction.')
  INTO author VALUES (5, 'Herman Melville', 'American novelist and poet, known for Moby-Dick.')
  INTO author VALUES (6, 'J.D. Salinger', 'American writer, known for The Catcher in the Rye.')
  INTO author VALUES (7, 'Charlotte Brontë', 'English novelist and poet.')
  INTO author VALUES (8, 'Emily Brontë', 'English novelist and poet, known for Wuthering Heights.')
  INTO author VALUES (9, 'Mary Shelley', 'English novelist, known for Frankenstein.')
  INTO author VALUES (10, 'Aldous Huxley', 'English writer, philosopher, and author of Brave New World.')
SELECT * FROM dual;

-- bookauthor: 10 rows
INSERT ALL
  INTO bookauthor VALUES (1, 1)
  INTO bookauthor VALUES (2, 2)
  INTO bookauthor VALUES (3, 3)
  INTO bookauthor VALUES (4, 4)
  INTO bookauthor VALUES (5, 5)
  INTO bookauthor VALUES (6, 6)
  INTO bookauthor VALUES (7, 7)
  INTO bookauthor VALUES (8, 8)
  INTO bookauthor VALUES (9, 9)
  INTO bookauthor VALUES (10, 2)
SELECT * FROM dual;

-- customer: 10 rows
INSERT ALL
  INTO customer VALUES (1, 'Alice Johnson')
  INTO customer VALUES (2, 'Bob Smith')
  INTO customer VALUES (3, 'Charlie Brown')
  INTO customer VALUES (4, 'Diana Prince')
  INTO customer VALUES (5, 'Eve Adams')
  INTO customer VALUES (6, 'Frank Castle')
  INTO customer VALUES (7, 'Grace Hopper')
  INTO customer VALUES (8, 'Hank Pym')
  INTO customer VALUES (9, 'Ivy League')
  INTO customer VALUES (10, 'Jack Ryan')
SELECT * FROM dual;

-- address: 10 rows
INSERT ALL
  INTO address VALUES (1, 1, '123 Maple Street', 'New York', 'NY', 'USA')
  INTO address VALUES (2, 2, '456 Oak Avenue', 'Los Angeles', 'CA', 'USA')
  INTO address VALUES (3, 3, '789 Pine Road', 'Chicago', 'IL', 'USA')
  INTO address VALUES (4, 4, '101 Birch Blvd', 'Houston', 'TX', 'USA')
  INTO address VALUES (5, 5, '202 Cedar Lane', 'Phoenix', 'AZ', 'USA')
  INTO address VALUES (6, 6, '303 Elm Drive', 'Philadelphia', 'PA', 'USA')
  INTO address VALUES (7, 7, '404 Walnut Way', 'San Antonio', 'TX', 'USA')
  INTO address VALUES (8, 8, '505 Chestnut Circle', 'San Diego', 'CA', 'USA')
  INTO address VALUES (9, 9, '606 Spruce Court', 'Dallas', 'TX', 'USA')
  INTO address VALUES (10, 10, '707 Fir Place', 'San Jose', 'CA', 'USA')
SELECT * FROM dual;

-- wishlist: 10 rows
INSERT ALL
  INTO wishlist VALUES (1, 1)
  INTO wishlist VALUES (1, 2)
  INTO wishlist VALUES (2, 3)
  INTO wishlist VALUES (3, 4)
  INTO wishlist VALUES (4, 5)
  INTO wishlist VALUES (5, 6)
  INTO wishlist VALUES (6, 7)
  INTO wishlist VALUES (7, 8)
  INTO wishlist VALUES (8, 9)
  INTO wishlist VALUES (9, 10)
SELECT * FROM dual;

-- orders: 10 rows
INSERT ALL
  INTO orders VALUES (1, TO_DATE('2023-06-01','YYYY-MM-DD'), 1, 'Credit Card', 'Shipped', 1)
  INTO orders VALUES (2, TO_DATE('2023-06-02','YYYY-MM-DD'), 2, 'PayPal', 'Processing', 2)
  INTO orders VALUES (3, TO_DATE('2023-06-03','YYYY-MM-DD'), 3, 'Debit Card', 'Delivered', 3)
  INTO orders VALUES (4, TO_DATE('2023-06-04','YYYY-MM-DD'), 4, 'Net Banking', 'Shipped', 4)
  INTO orders VALUES (5, TO_DATE('2023-06-05','YYYY-MM-DD'), 5, 'Credit Card', 'Processing', 5)
  INTO orders VALUES (6, TO_DATE('2023-06-06','YYYY-MM-DD'), 6, 'PayPal', 'Delivered', 6)
  INTO orders VALUES (7, TO_DATE('2023-06-07','YYYY-MM-DD'), 7, 'Credit Card', 'Shipped', 7)
  INTO orders VALUES (8, TO_DATE('2023-06-08','YYYY-MM-DD'), 8, 'Debit Card', 'Processing', 8)
  INTO orders VALUES (9, TO_DATE('2023-06-09','YYYY-MM-DD'), 9, 'Net Banking', 'Delivered', 9)
  INTO orders VALUES (10, TO_DATE('2023-06-10','YYYY-MM-DD'), 10, 'Credit Card', 'Shipped', 10)
SELECT * FROM dual;

-- order_book: 10 rows
INSERT ALL
  INTO order_book VALUES (1, 1, 1, 1, 0.0)
  INTO order_book VALUES (2, 2, 2, 2, 5.0)
  INTO order_book VALUES (3, 3, 3, 1, 10.0)
  INTO order_book VALUES (4, 4, 4, 3, 0.0)
  INTO order_book VALUES (5, 5, 5, 2, 15.0)
  INTO order_book VALUES (6, 6, 6, 1, 0.0)
  INTO order_book VALUES (7, 7, 7, 2, 5.0)
  INTO order_book VALUES (8, 8, 8, 1, 10.0)
  INTO order_book VALUES (9, 9, 9, 3, 0.0)
  INTO order_book VALUES (10, 10, 10, 2, 15.0)
SELECT * FROM dual;

COMMIT;
EXIT;
